# This is the beginning of the numpy tutorial

In [1]:
print("Heghgllo World")

Heghgllo World


In [2]:
for i in range(20):
    print("Hello World")

Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World


In [ ]:
import pandas as pd

In [10]:
!pip install numpy

In [13]:
import numpy as np 

# This is how we print 2d arrays, 2 list inside the array.

In [16]:
b = np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
# 2d array--> an array inside an array.
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [19]:
# get no of direction of the array b.
b.ndim

2

In [20]:
# get the shatpe of the array b
b.shape

(2, 6)

In [23]:
# get the data type of the array
b.dtype

dtype('int32')

In [26]:
# get size,  will return the size of each item in the array.
b.itemsize

4

In [27]:
b.size  # get the no of elements in the array.

12

In [35]:
# get the total size of the array, 2 ways
print("Method 1-->",b.size*b.itemsize)
print("Method 1--> " + str(b.size*b.itemsize))
print("Method 2-->",b.nbytes)

Method 1--> 48
Method 1--> 48
Method 2--> 48


Accessing or changing specific rows, columns, etc.

In [39]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# 2/7 array(R-2, C-7)
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [40]:
a.shape

(2, 7)

In [47]:
# Get a specific element----> array[r,c],  indexing, counting starts from 0.
# first row, 7th element.
a[0, 6]


7

In [49]:
#Get the whole row
a[0, :] # get the first row.

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
# Gettin the 3rd column
a[:, 2] # Get all of 3rd column

array([ 3, 10])

In [60]:
# Jump sequentially [startIndex:endindex:stepsize]
# it is 2d array, so index is 2d.
# the end is exclusive.
# [r:c:stepsize]
# [1st to 2nd row: 1st to 7 column: step size 2]

a[0:2, 0:7:2]



array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [62]:
# change specific element in the array.
a[1,5] = 20; # 2nd row, 6th column
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# 3d array

In [66]:
d = np.array([[[1,2],[3,5]],[[1,35],[3,37]]])
# 3d array, an array inside an array inside an array.
print(d)

[[[ 1  2]
  [ 3  5]]

 [[ 1 35]
  [ 3 37]]]


In [67]:
d.ndim

3

In [69]:
d.shape

(2, 2, 2)

In [70]:
three_d_array = np.array([[[1, 2, 3, 4],
                            [5, 6, 7, 8],
                            [9, 10, 11, 12]],
                           [[13, 14, 15, 16],
                            [17, 18, 19, 20],
                            [21, 22, 23, 24]]])

In [71]:
three_d_array.shape

(2, 3, 4)

This means 2 (3X4) matrix.

Usefull matrix creation stuff

In [74]:
np.ones((2,2), dtype='int32') 
# 1 2X2 matrix filled with one

array([[1, 1],
       [1, 1]])

In [76]:
np.full((2,2,3), 99)
# this syntax is different from previous one.

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [77]:
# Initialise an array of random numbers
np.random.rand(3,4)

array([[0.28923804, 0.97678069, 0.56375867, 0.87690267],
       [0.05406939, 0.60889072, 0.36369516, 0.32538726],
       [0.45330931, 0.5703794 , 0.78010997, 0.79598015]])