In [9]:
import numpy as np

List Vs numpy Process Time 

In [4]:
# importing process-time from time
from time import process_time

list = [i for i in range(10000000)]
# Makes a list from 1 to 10000. i is the placeholder
start_time = process_time()
Nlist = [i+5 for i in list]
end_time = process_time()
print (end_time-start_time)

0.421875


In [18]:
#Now using numpy array
np_array = np.array([i for i in range(100000000)])
start_time = process_time()
print("The start time is " + str(start_time))
# print("The start time is" + start_time)
np_array+=5
end_time = process_time()
print("The end time is " + str((end_time)))
print (end_time - start_time)

The start time is 76.859375
The end time is 76.9375
0.078125


Numpy array

In [2]:
list1 = [1,2,3,4,5,6,7,8,9,0]
print (list1)
type(list1) # returns the type. 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


list

In [22]:
# Creating an array of numpy array
Narray = np.array([1,4,6,78,77,0]) # using th numpy library to create an array called Narray
print(Narray) # returns a 1d matrix
type(Narray) # n- dimension array.

[ 1  4  6 78 77  0]


numpy.ndarray

# Creating a 1 dimensional arrary
a = np.array([1,4,7,9,4])
print(a)

In [24]:
a.shape  # rXc     only 5

(5,)

In [27]:
b = np.array([(1,2,3,4,5),(6,7,8,9,0)])
print(b)
b.shape #    2x5

[[1 2 3 4 5]
 [6 7 8 9 0]]


(2, 5)

In [29]:
c = np.array([(1,2,3,4,5),(6,7,8,9,0)], dtype = float)
print(c) # floating point values

[[1. 2. 3. 4. 5.]
 [6. 7. 8. 9. 0.]]


Initial placeholders in numpy arrays

In [33]:
# Create a numpy of Zeros
d = np.zeros((4,4))
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
# Create a numpy of 5
e = np.full((2,3),5)
print(e)


[[5 5 5]
 [5 5 5]]


In [38]:
# Create an identity matrix
i = np.eye(4)   # identity matrix is nxn
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
# Create a numpy array of random numbers
r = np.random.random((2,2))
print(r)

[[0.75362846 0.18157299]
 [0.80064209 0.4706596 ]]


In [42]:
#Create a numpy array of random integers
ri = np.random.randint(1,100,(5,5)) # range is 1 to 100  5x5 matrix 
print(ri)

[[63 91 17 54 68]
 [38 21 67 38 11]
 [66 34 44 98 62]
 [27 46 63 49 13]
 [12 42 60 48 55]]


In [46]:
# Creating an array of evenly spaced numbers 
e = np.arange(0,100,10) # not inclusive of the last number 
print(e)

[ 0 10 20 30 40 50 60 70 80 90]


In [49]:
#Convert a normal list into numpy array
x = [2,5,74,63,6,834,6]
cL = np.asarray(x)
type(cL) # numpy array of n dimension

numpy.ndarray

Analysing a numpy array

In [50]:
# Checking the number of elements in the matrix 
print(cL.size)

7


In [51]:
# no of dimension
print(cL.ndim)

1


# If you add a list, it concatonates,
# But if you add numpy list(Matrix) , it adds like matrix addition
# the division, multiplication and subtraction is also same as traditional matrix operation.